<?php

namespace ContainerMXbF3vo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Wn101mGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Wn101mG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Wn101mG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'uploaderService' => ['privates', 'App\\Service\\UploaderService', 'getUploaderServiceService', true],
        ], [
            'uploaderService' => 'App\\Service\\UploaderService',
        ]);
    }
}
