<?php

namespace ContainerMXbF3vo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUniqueCategoryNameValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Validator\UniqueCategoryNameValidator' shared autowired service.
     *
     * @return \App\Validator\UniqueCategoryNameValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Validator\\UniqueCategoryNameValidator'] = new \App\Validator\UniqueCategoryNameValidator();
    }
}
