<?php

namespace ContainerXMW2hdM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUniqueCategoryNameValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Validator\UniqueCategoryNameValidator' shared autowired service.
     *
     * @return \App\Validator\UniqueCategoryNameValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'validator'.\DIRECTORY_SEPARATOR.'ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'validator'.\DIRECTORY_SEPARATOR.'ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Validator'.\DIRECTORY_SEPARATOR.'UniqueCategoryNameValidator.php';

        return $container->privates['App\\Validator\\UniqueCategoryNameValidator'] = new \App\Validator\UniqueCategoryNameValidator(($container->privates['App\\Repository\\RestaurantCategoryRepository'] ?? $container->load('getRestaurantCategoryRepositoryService')));
    }
}
