knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltopdf  # Chemin vers l'exécutable wkhtmltopdf
        options:    []
    image:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltoimage  # Chemin vers l'exécutable wkhtmltoimage
        options:    []
