<?php

namespace ContainerQGONz67;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.GZ8iKbh.App\Entity\Commande' shared service.
     *
     * @return \App\Entity\Commande
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.GZ8iKbh": it references class "App\\Entity\\Commande" but no such service exists.');
    }
}
