<?php

namespace ContainerIesygSF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YYeQTLNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YYeQTLN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YYeQTLN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ClientRepository' => ['privates', 'App\\Repository\\ClientRepository', 'getClientRepositoryService', true],
            'twig' => ['services', '.container.private.twig', 'get_Container_Private_TwigService', false],
        ], [
            'ClientRepository' => 'App\\Repository\\ClientRepository',
            'twig' => '?',
        ]);
    }
}
