<?php

namespace ContainerAjHZP1E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRestaurantCategory2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._Rc1vP2.App\Entity\RestaurantCategory' shared service.
     *
     * @return \App\Entity\RestaurantCategory
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator._Rc1vP2": it references class "App\\Entity\\RestaurantCategory" but no such service exists.');
    }
}
