<?php

namespace ContainerIpaE0Zm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JLpDTADService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JLpDTAD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JLpDTAD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\MainController::index' => ['privates', '.service_locator.sH7lAPV', 'get_ServiceLocator_SH7lAPVService', true],
            'App\\Controller\\PlatController::delete' => ['privates', '.service_locator.VQtysSJ', 'get_ServiceLocator_VQtysSJService', true],
            'App\\Controller\\PlatController::edit' => ['privates', '.service_locator.VQtysSJ', 'get_ServiceLocator_VQtysSJService', true],
            'App\\Controller\\PlatController::index' => ['privates', '.service_locator.687CVbR', 'get_ServiceLocator_687CVbRService', true],
            'App\\Controller\\PlatController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\PlatController::show' => ['privates', '.service_locator.VLAmfmc', 'get_ServiceLocator_VLAmfmcService', true],
            'App\\Controller\\RestaurantCategoryController::delete' => ['privates', '.service_locator.DN2cqWN', 'get_ServiceLocator_DN2cqWNService', true],
            'App\\Controller\\RestaurantCategoryController::edit' => ['privates', '.service_locator.DN2cqWN', 'get_ServiceLocator_DN2cqWNService', true],
            'App\\Controller\\RestaurantCategoryController::getRestaurants' => ['privates', '.service_locator.BWa68rC', 'get_ServiceLocator_BWa68rCService', true],
            'App\\Controller\\RestaurantCategoryController::index' => ['privates', '.service_locator.sH7lAPV', 'get_ServiceLocator_SH7lAPVService', true],
            'App\\Controller\\RestaurantCategoryController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\RestaurantCategoryController::show' => ['privates', '.service_locator._Rc1vP2', 'get_ServiceLocator_Rc1vP2Service', true],
            'App\\Controller\\RestaurantController::delete' => ['privates', '.service_locator.Hc8H.Su', 'get_ServiceLocator_Hc8H_SuService', true],
            'App\\Controller\\RestaurantController::edit' => ['privates', '.service_locator.Hc8H.Su', 'get_ServiceLocator_Hc8H_SuService', true],
            'App\\Controller\\RestaurantController::index' => ['privates', '.service_locator.BWa68rC', 'get_ServiceLocator_BWa68rCService', true],
            'App\\Controller\\RestaurantController::restaurantsByCategory' => ['privates', '.service_locator.gh0oFS6', 'get_ServiceLocator_Gh0oFS6Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\MainController:index' => ['privates', '.service_locator.sH7lAPV', 'get_ServiceLocator_SH7lAPVService', true],
            'App\\Controller\\PlatController:delete' => ['privates', '.service_locator.VQtysSJ', 'get_ServiceLocator_VQtysSJService', true],
            'App\\Controller\\PlatController:edit' => ['privates', '.service_locator.VQtysSJ', 'get_ServiceLocator_VQtysSJService', true],
            'App\\Controller\\PlatController:index' => ['privates', '.service_locator.687CVbR', 'get_ServiceLocator_687CVbRService', true],
            'App\\Controller\\PlatController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\PlatController:show' => ['privates', '.service_locator.VLAmfmc', 'get_ServiceLocator_VLAmfmcService', true],
            'App\\Controller\\RestaurantCategoryController:delete' => ['privates', '.service_locator.DN2cqWN', 'get_ServiceLocator_DN2cqWNService', true],
            'App\\Controller\\RestaurantCategoryController:edit' => ['privates', '.service_locator.DN2cqWN', 'get_ServiceLocator_DN2cqWNService', true],
            'App\\Controller\\RestaurantCategoryController:getRestaurants' => ['privates', '.service_locator.BWa68rC', 'get_ServiceLocator_BWa68rCService', true],
            'App\\Controller\\RestaurantCategoryController:index' => ['privates', '.service_locator.sH7lAPV', 'get_ServiceLocator_SH7lAPVService', true],
            'App\\Controller\\RestaurantCategoryController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\RestaurantCategoryController:show' => ['privates', '.service_locator._Rc1vP2', 'get_ServiceLocator_Rc1vP2Service', true],
            'App\\Controller\\RestaurantController:delete' => ['privates', '.service_locator.Hc8H.Su', 'get_ServiceLocator_Hc8H_SuService', true],
            'App\\Controller\\RestaurantController:edit' => ['privates', '.service_locator.Hc8H.Su', 'get_ServiceLocator_Hc8H_SuService', true],
            'App\\Controller\\RestaurantController:index' => ['privates', '.service_locator.BWa68rC', 'get_ServiceLocator_BWa68rCService', true],
            'App\\Controller\\RestaurantController:restaurantsByCategory' => ['privates', '.service_locator.gh0oFS6', 'get_ServiceLocator_Gh0oFS6Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\MainController::index' => '?',
            'App\\Controller\\PlatController::delete' => '?',
            'App\\Controller\\PlatController::edit' => '?',
            'App\\Controller\\PlatController::index' => '?',
            'App\\Controller\\PlatController::new' => '?',
            'App\\Controller\\PlatController::show' => '?',
            'App\\Controller\\RestaurantCategoryController::delete' => '?',
            'App\\Controller\\RestaurantCategoryController::edit' => '?',
            'App\\Controller\\RestaurantCategoryController::getRestaurants' => '?',
            'App\\Controller\\RestaurantCategoryController::index' => '?',
            'App\\Controller\\RestaurantCategoryController::new' => '?',
            'App\\Controller\\RestaurantCategoryController::show' => '?',
            'App\\Controller\\RestaurantController::delete' => '?',
            'App\\Controller\\RestaurantController::edit' => '?',
            'App\\Controller\\RestaurantController::index' => '?',
            'App\\Controller\\RestaurantController::restaurantsByCategory' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\MainController:index' => '?',
            'App\\Controller\\PlatController:delete' => '?',
            'App\\Controller\\PlatController:edit' => '?',
            'App\\Controller\\PlatController:index' => '?',
            'App\\Controller\\PlatController:new' => '?',
            'App\\Controller\\PlatController:show' => '?',
            'App\\Controller\\RestaurantCategoryController:delete' => '?',
            'App\\Controller\\RestaurantCategoryController:edit' => '?',
            'App\\Controller\\RestaurantCategoryController:getRestaurants' => '?',
            'App\\Controller\\RestaurantCategoryController:index' => '?',
            'App\\Controller\\RestaurantCategoryController:new' => '?',
            'App\\Controller\\RestaurantCategoryController:show' => '?',
            'App\\Controller\\RestaurantController:delete' => '?',
            'App\\Controller\\RestaurantController:edit' => '?',
            'App\\Controller\\RestaurantController:index' => '?',
            'App\\Controller\\RestaurantController:restaurantsByCategory' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
