<?php

namespace ContainerIpaE0Zm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotNullIfSetValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Validator\NotNullIfSetValidator' shared autowired service.
     *
     * @return \App\Validator\NotNullIfSetValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Validator\\NotNullIfSetValidator'] = new \App\Validator\NotNullIfSetValidator();
    }
}
