<?php

namespace ContainerIpaE0Zm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlatControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PlatController' shared autowired service.
     *
     * @return \App\Controller\PlatController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\PlatController'] = $instance = new \App\Controller\PlatController();

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\PlatController', $container));

        return $instance;
    }
}
