<?php

namespace ContainerIpaE0Zm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReclamationRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\ReclamationRepository' shared autowired service.
     *
     * @return \App\Repository\ReclamationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ReclamationRepository'] = new \App\Repository\ReclamationRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
