<?php

namespace ContainerDGq00Rg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UlnNO2UService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ulnNO2U' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ulnNO2U'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'restaurantCategory' => ['privates', '.errored.7gJ9lA9', NULL, 'Cannot determine controller argument for "App\\Controller\\RestaurantCategoryController::delete()": the $restaurantCategory argument is type-hinted with the non-existent class or interface: "App\\Entity\\RestaurantCategory".'],
        ], [
            'entityManager' => '?',
            'restaurantCategory' => '?',
        ]);
    }
}
