<?php

namespace ContainerDGq00Rg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_Ci3wrwiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.ci3wrwi' shared service.
     *
     * @return \App\Entity\Restaurant
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\RestaurantController::delete()": the $restaurant argument is type-hinted with the non-existent class or interface: "App\\Entity\\Restaurant".');
    }
}
