<?php

namespace ContainerDGq00Rg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F7QdaPaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.f7QdaPa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.f7QdaPa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'restaurantCategory' => ['privates', '.errored.SEzr3zN', NULL, 'Cannot determine controller argument for "App\\Controller\\RestaurantCategoryController::show()": the $restaurantCategory argument is type-hinted with the non-existent class or interface: "App\\Entity\\RestaurantCategory".'],
        ], [
            'restaurantCategory' => '?',
        ]);
    }
}
