<?php

namespace ContainerDGq00Rg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B4rRPCYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.B4rRPCY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.B4rRPCY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'plat' => ['privates', '.errored.wwcutAI', NULL, 'Cannot determine controller argument for "App\\Controller\\PlatController::edit()": the $plat argument is type-hinted with the non-existent class or interface: "App\\Entity\\Plat".'],
        ], [
            'entityManager' => '?',
            'plat' => '?',
        ]);
    }
}
