<?php

namespace ContainerDGq00Rg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_SEzr3zNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.SEzr3zN' shared service.
     *
     * @return \App\Entity\RestaurantCategory
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\RestaurantCategoryController::show()": the $restaurantCategory argument is type-hinted with the non-existent class or interface: "App\\Entity\\RestaurantCategory".');
    }
}
