<?php

namespace ContainerDGq00Rg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_D5bqKBHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.d5bqKBH' shared service.
     *
     * @return \App\Entity\Plat
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\PlatController::show()": the $plat argument is type-hinted with the non-existent class or interface: "App\\Entity\\Plat".');
    }
}
