<?php

namespace ContainerDGq00Rg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_M2LTy7XService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.M2LTy7X' shared service.
     *
     * @return \App\Entity\Restaurant
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\RestaurantController::edit()": the $restaurant argument is type-hinted with the non-existent class or interface: "App\\Entity\\Restaurant".');
    }
}
