<?php

namespace ContainerCjzzuDo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSmsGeneratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\SmsGenerator' shared autowired service.
     *
     * @return \App\Service\SmsGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'SmsGenerator.php';

        return $container->privates['App\\Service\\SmsGenerator'] = new \App\Service\SmsGenerator();
    }
}
