<?php

namespace ContainerZc1dToH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NIEOpo9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nIEOpo9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nIEOpo9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'participation' => ['privates', '.errored..service_locator.nIEOpo9.App\\Entity\\Participation', NULL, 'Cannot autowire service ".service_locator.nIEOpo9": it references class "App\\Entity\\Participation" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'participation' => 'App\\Entity\\Participation',
        ]);
    }
}
