<?php

namespace ContainerIt0nKVe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEvaluationRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\EvaluationRepository' shared autowired service.
     *
     * @return \App\Repository\EvaluationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\EvaluationRepository'] = new \App\Repository\EvaluationRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
