<?php

namespace ContainerIt0nKVe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRestaurantControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\RestaurantController' shared autowired service.
     *
     * @return \App\Controller\RestaurantController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\RestaurantController'] = $instance = new \App\Controller\RestaurantController();

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\RestaurantController', $container));

        return $instance;
    }
}
