<?php

namespace ContainerIt0nKVe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRestaurantTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\RestaurantType' shared autowired service.
     *
     * @return \App\Form\RestaurantType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\RestaurantType'] = new \App\Form\RestaurantType();
    }
}
