<?php

namespace ContainerIt0nKVe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRestaurantCategoryTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\RestaurantCategoryType' shared autowired service.
     *
     * @return \App\Form\RestaurantCategoryType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\RestaurantCategoryType'] = new \App\Form\RestaurantCategoryType();
    }
}
