<?php

namespace ContainerUYzxmWQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRestaurantCategoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.DN2cqWN.App\Entity\RestaurantCategory' shared service.
     *
     * @return \App\Entity\RestaurantCategory
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.DN2cqWN": it references class "App\\Entity\\RestaurantCategory" but no such service exists.');
    }
}
