<?php

namespace ContainerA1YJCn1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J000wrwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.j000wrw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.j000wrw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'avisRepository' => ['privates', 'App\\Repository\\AvisRepository', 'getAvisRepositoryService', true],
            'platRepository' => ['privates', 'App\\Repository\\PlatRepository', 'getPlatRepositoryService', true],
        ], [
            'avisRepository' => 'App\\Repository\\AvisRepository',
            'platRepository' => 'App\\Repository\\PlatRepository',
        ]);
    }
}
