<?php

namespace ContainerA1YJCn1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GfBJ35NService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gfBJ35N' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gfBJ35N'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'evaluationRepository' => ['privates', 'App\\Repository\\evaluationRepository', 'getEvaluationRepositoryService', true],
            'pdf' => ['services', 'knp_snappy.pdf', 'getKnpSnappy_PdfService', true],
        ], [
            'evaluationRepository' => 'App\\Repository\\evaluationRepository',
            'pdf' => '?',
        ]);
    }
}
