<?php

namespace ContainerA1YJCn1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OaqQmZSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OaqQmZS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OaqQmZS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'encoder' => ['services', '.container.private.security.password_encoder', 'get_Container_Private_Security_PasswordEncoderService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'smsGenerator' => ['privates', 'App\\Service\\SmsGenerator', 'getSmsGeneratorService', true],
            'uploaderService' => ['privates', 'App\\Service\\UploaderService', 'getUploaderServiceService', true],
        ], [
            'encoder' => '?',
            'mailer' => '?',
            'smsGenerator' => 'App\\Service\\SmsGenerator',
            'uploaderService' => 'App\\Service\\UploaderService',
        ]);
    }
}
