<?php

namespace ContainerA1YJCn1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gy6q6VOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gy6q6VO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gy6q6VO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'evaluationRepository' => ['privates', 'App\\Repository\\evaluationRepository', 'getEvaluationRepositoryService', true],
        ], [
            'evaluationRepository' => 'App\\Repository\\evaluationRepository',
        ]);
    }
}
