<?php

namespace ContainerX3RxyoQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Zk0sGNdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zk0sGNd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zk0sGNd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ClientController::back' => ['privates', '.service_locator.T1Cqnaw', 'get_ServiceLocator_T1CqnawService', true],
            'App\\Controller\\ClientController::banClient' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ClientController::confirmEmail' => ['privates', '.service_locator.tzJsoZL', 'get_ServiceLocator_TzJsoZLService', true],
            'App\\Controller\\ClientController::confirmSms' => ['privates', '.service_locator.tzJsoZL', 'get_ServiceLocator_TzJsoZLService', true],
            'App\\Controller\\ClientController::createCompte' => ['privates', '.service_locator.OaqQmZS', 'get_ServiceLocator_OaqQmZSService', true],
            'App\\Controller\\ClientController::deleteClient' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ClientController::editClient' => ['privates', '.service_locator.tXM58lC', 'get_ServiceLocator_TXM58lCService', true],
            'App\\Controller\\ClientController::editc' => ['privates', '.service_locator.Wn101mG', 'get_ServiceLocator_Wn101mGService', true],
            'App\\Controller\\ClientController::editprivacy' => ['privates', '.service_locator.tXM58lC', 'get_ServiceLocator_TXM58lCService', true],
            'App\\Controller\\ClientController::forgotmdp' => ['privates', '.service_locator.1I1MNFX', 'get_ServiceLocator_1I1MNFXService', true],
            'App\\Controller\\ClientController::front' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ClientController::search' => ['privates', '.service_locator.YYeQTLN', 'get_ServiceLocator_YYeQTLNService', true],
            'App\\Controller\\ClientController::unbanClient' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ClientController::verifmdp' => ['privates', '.service_locator.dBnDYM8', 'get_ServiceLocator_DBnDYM8Service', true],
            'App\\Controller\\SecurityController::authenticate' => ['privates', '.service_locator.5n4Prsd', 'get_ServiceLocator_5n4PrsdService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\ClientController:back' => ['privates', '.service_locator.T1Cqnaw', 'get_ServiceLocator_T1CqnawService', true],
            'App\\Controller\\ClientController:banClient' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ClientController:confirmEmail' => ['privates', '.service_locator.tzJsoZL', 'get_ServiceLocator_TzJsoZLService', true],
            'App\\Controller\\ClientController:confirmSms' => ['privates', '.service_locator.tzJsoZL', 'get_ServiceLocator_TzJsoZLService', true],
            'App\\Controller\\ClientController:createCompte' => ['privates', '.service_locator.OaqQmZS', 'get_ServiceLocator_OaqQmZSService', true],
            'App\\Controller\\ClientController:deleteClient' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ClientController:editClient' => ['privates', '.service_locator.tXM58lC', 'get_ServiceLocator_TXM58lCService', true],
            'App\\Controller\\ClientController:editc' => ['privates', '.service_locator.Wn101mG', 'get_ServiceLocator_Wn101mGService', true],
            'App\\Controller\\ClientController:editprivacy' => ['privates', '.service_locator.tXM58lC', 'get_ServiceLocator_TXM58lCService', true],
            'App\\Controller\\ClientController:forgotmdp' => ['privates', '.service_locator.1I1MNFX', 'get_ServiceLocator_1I1MNFXService', true],
            'App\\Controller\\ClientController:front' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ClientController:search' => ['privates', '.service_locator.YYeQTLN', 'get_ServiceLocator_YYeQTLNService', true],
            'App\\Controller\\ClientController:unbanClient' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ClientController:verifmdp' => ['privates', '.service_locator.dBnDYM8', 'get_ServiceLocator_DBnDYM8Service', true],
            'App\\Controller\\SecurityController:authenticate' => ['privates', '.service_locator.5n4Prsd', 'get_ServiceLocator_5n4PrsdService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\ClientController::back' => '?',
            'App\\Controller\\ClientController::banClient' => '?',
            'App\\Controller\\ClientController::confirmEmail' => '?',
            'App\\Controller\\ClientController::confirmSms' => '?',
            'App\\Controller\\ClientController::createCompte' => '?',
            'App\\Controller\\ClientController::deleteClient' => '?',
            'App\\Controller\\ClientController::editClient' => '?',
            'App\\Controller\\ClientController::editc' => '?',
            'App\\Controller\\ClientController::editprivacy' => '?',
            'App\\Controller\\ClientController::forgotmdp' => '?',
            'App\\Controller\\ClientController::front' => '?',
            'App\\Controller\\ClientController::search' => '?',
            'App\\Controller\\ClientController::unbanClient' => '?',
            'App\\Controller\\ClientController::verifmdp' => '?',
            'App\\Controller\\SecurityController::authenticate' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ClientController:back' => '?',
            'App\\Controller\\ClientController:banClient' => '?',
            'App\\Controller\\ClientController:confirmEmail' => '?',
            'App\\Controller\\ClientController:confirmSms' => '?',
            'App\\Controller\\ClientController:createCompte' => '?',
            'App\\Controller\\ClientController:deleteClient' => '?',
            'App\\Controller\\ClientController:editClient' => '?',
            'App\\Controller\\ClientController:editc' => '?',
            'App\\Controller\\ClientController:editprivacy' => '?',
            'App\\Controller\\ClientController:forgotmdp' => '?',
            'App\\Controller\\ClientController:front' => '?',
            'App\\Controller\\ClientController:search' => '?',
            'App\\Controller\\ClientController:unbanClient' => '?',
            'App\\Controller\\ClientController:verifmdp' => '?',
            'App\\Controller\\SecurityController:authenticate' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
