<?php

namespace ContainerBvPLXbd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O6PoTCJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.o6PoTCJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.o6PoTCJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'evaluation' => ['privates', '.errored..service_locator.o6PoTCJ.App\\Entity\\Evaluation', NULL, 'Cannot autowire service ".service_locator.o6PoTCJ": it references class "App\\Entity\\Evaluation" but no such service exists.'],
        ], [
            'evaluation' => 'App\\Entity\\Evaluation',
        ]);
    }
}
