<?php

namespace ContainerFmBKy6e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_KaaR0UkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.kaaR0Uk' shared service.
     *
     * @return \App\Controller\EvenementRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\EvenementController::showfront()": the $evenementRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\EvenementRepository". Did you forget to add a use statement?');
    }
}
