<?php

namespace ContainerFmBKy6e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IFoY6ODService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iFoY6OD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iFoY6OD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'evenement' => ['privates', '.errored..service_locator.iFoY6OD.App\\Entity\\Evenement', NULL, 'Cannot autowire service ".service_locator.iFoY6OD": it references class "App\\Entity\\Evenement" but no such service exists.'],
            'evenementRepository' => ['privates', '.errored.kaaR0Uk', NULL, 'Cannot determine controller argument for "App\\Controller\\EvenementController::showfront()": the $evenementRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\EvenementRepository". Did you forget to add a use statement?'],
        ], [
            'evenement' => 'App\\Entity\\Evenement',
            'evenementRepository' => '?',
        ]);
    }
}
