<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAxyNAAx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAxyNAAx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAxyNAAx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAxyNAAx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAxyNAAx\App_KernelDevDebugContainer([
    'container.build_hash' => 'AxyNAAx',
    'container.build_id' => '7d2f044b',
    'container.build_time' => 1714468791,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAxyNAAx');
