<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX3RxyoQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX3RxyoQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX3RxyoQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX3RxyoQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX3RxyoQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'X3RxyoQ',
    'container.build_id' => '75426dee',
    'container.build_time' => 1714244561,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX3RxyoQ');
