<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_evenement_index' => [[], ['_controller' => 'App\\Controller\\EvenementController::index'], [], [['text', '/evenement/']], [], [], []],
    'app_evenement_new' => [[], ['_controller' => 'App\\Controller\\EvenementController::new'], [], [['text', '/evenement/new']], [], [], []],
    'app_evenement_show' => [['idEvent'], ['_controller' => 'App\\Controller\\EvenementController::show'], [], [['variable', '/', '[^/]++', 'idEvent', true], ['text', '/evenement']], [], [], []],
    'app_evenement_edit' => [['idEvent'], ['_controller' => 'App\\Controller\\EvenementController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'idEvent', true], ['text', '/evenement']], [], [], []],
    'app_evenement_delete' => [['idEvent'], ['_controller' => 'App\\Controller\\EvenementController::delete'], [], [['variable', '/', '[^/]++', 'idEvent', true], ['text', '/evenement']], [], [], []],
    'app_participation_index' => [[], ['_controller' => 'App\\Controller\\ParticipationController::index'], [], [['text', '/participation/']], [], [], []],
    'app_participation_new' => [[], ['_controller' => 'App\\Controller\\ParticipationController::new'], [], [['text', '/participation/new']], [], [], []],
    'app_participation_edit' => [['idP'], ['_controller' => 'App\\Controller\\ParticipationController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'idP', true], ['text', '/participation']], [], [], []],
    'app_participation_delete' => [['idP'], ['_controller' => 'App\\Controller\\ParticipationController::delete'], [], [['variable', '/', '[^/]++', 'idP', true], ['text', '/participation']], [], [], []],
    'app_qr_codes' => [[], ['_controller' => 'App\\Controller\\QrCodeGeneratorController::index'], [], [['text', '/qr-codes']], [], [], []],
    'qr_code_generate' => [['builder', 'data'], ['_controller' => 'Endroid\\QrCodeBundle\\Controller\\GenerateController'], ['data' => '[\\w\\W]+'], [['variable', '/', '[\\w\\W]+', 'data', true], ['variable', '/', '[^/]++', 'builder', true], ['text', '/qr-code']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'app_participation_show' => [['idP'], ['_controller' => 'App\\Controller\\ParticipationController::show'], [], [['variable', '/', '[^/]++', 'idP', true], ['text', '/show']], [], [], []],
    'app_front' => [[], ['_controller' => 'App\\Controller\\ParticipationController::front'], [], [['text', '/front']], [], [], []],
    'app_back' => [[], ['_controller' => 'App\\Controller\\EvenementController::back'], [], [['text', '/back']], [], [], []],
    'app_evenement_frontindex' => [[], ['_controller' => 'App\\Controller\\EvenementController::frontindex'], [], [['text', '/frontindex']], [], [], []],
    'app_evenement_showfront' => [['idEvent'], ['_controller' => 'App\\Controller\\EvenementController::showfront'], [], [['variable', '/', '[^/]++', 'idEvent', true], ['text', '/showfront']], [], [], []],
];
